export const ERROR_CODE = {
  COMMON_BAD_REQUEST: 'COMMON_BAD_REQUEST',
  COMMON_VALIDATION_ERROR: 'COMMON_VALIDATION_ERROR',
  COMMON_UNAUTHORIZED: 'COMMON_UNAUTHORIZED',
  COMMON_FORBIDDEN: 'COMMON_FORBIDDEN',
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  COMMON_CONFLICT: 'COMMON_CONFLICT',
  COMMON_TOO_MANY_REQUESTS: 'COMMON_TOO_MANY_REQUESTS',
  COMMON_INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
