version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Seoul
    open-pull-requests-limit: 1
    groups:
      npm-version-updates:
        applies-to: version-updates
        patterns:
          - '*'
      npm-security-updates:
        applies-to: security-updates
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Seoul
    open-pull-requests-limit: 1
    groups:
      github-actions-version-updates:
        applies-to: version-updates
        patterns:
          - '*'
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - '*'
