ALTER TABLE "ClubUser"
ADD COLUMN "requestedAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "joinMessage" VARCHAR(300) NOT NULL DEFAULT '';

UPDATE "ClubUser"
SET "requestedAt" = "joinedAt";

ALTER TABLE "ClubUser"
ALTER COLUMN "joinedAt" DROP NOT NULL,
ALTER COLUMN "joinedAt" DROP DEFAULT;
